# Generated by Django 3.2.7 on 2021-10-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200404_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='send_notification',
            field=models.BooleanField(default=True, help_text='Aceito receber notificações por e-mail do Encontros Digitais', verbose_name='Aceitar notificações'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
