# Generated by Django 3.0.3 on 2020-04-04 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-is_answer', '-total_votes', '-timestamp'], 'verbose_name': 'Answer', 'verbose_name_plural': 'Answers'},
        ),
    ]
